### PR TITLE
Fix `Content-Length` header

### PR DESCRIPTION
**Pull request by bash**

### CODE REVIEW

**Comment by SergioBenitez** [comment]
So much for consts helping us avoid typos.

Can you add a test to make sure this never happens again?

**Comment by SergioBenitez** [comment]
Adding the test and merging this now.

**Comment by SergioBenitez** [comment]
Thanks for catching and fixing this. Merged in 35a1cf12b6b2f2cf4c699153f4f7938ca289bd7d.

**Comment by bash** [comment]
Wow, thanks for merging this so promptly! (I should really stop depending on master 😆)

I originally wanted to write a test, but ran into the second problem that you fixed in your commit, namely that the header is not visible to local clients.

**Pull request closed without merging**
